apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: selahcloudnewbadstore 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selahcloudnewbadstore 
    spec:
      containers:
        - name: selahcloudnewbadstore 
          image: cicdaksregistry.azurecr.io/selahcloudnewbadstore
          ports:
          - containerPort: 80