apiVersion: v1
kind: Service
metadata:
    name: selahcloudnewbadstorestaging
spec:
    type: LoadBalancer
    ports:
    - port: 8888
      targetPort: 80	
    selector:
        app: selahcloudnewbadstorestaging
